# Generated by Django 3.0.7 on 2020-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='upload_images')),
            ],
        ),
        migrations.CreateModel(
            name='SheetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('sheet', models.FileField(upload_to='upload_sheets')),
            ],
        ),
    ]
